### ISSUE TITLE
VTB补  kenlos全家桶

### ISSUE THREAD

**Issue by yfk2012** [bilibili-dd-center/vdb#38]
https://space.bilibili.com/9105683
https://space.bilibili.com/12918458/
https://space.bilibili.com/427477705/
https://space.bilibili.com/275267207/
https://space.bilibili.com/26585010/
https://space.bilibili.com/392573834/
https://space.bilibili.com/29382318/

**Comment by simon300000** [comment]
kenlos真的好多人啊

**Comment by yfk2012** [comment]
對呀23333
