### ISSUE TITLE
VTB补

### ISSUE THREAD

**Issue by C-JIUJIE** [bilibili-dd-center/vdb#5]
这里写上个人空间连接就行了
https://space.bilibili.com/282994?from=search&seid=11236209766001028723(๑•̀ㅂ•́)√

**Comment by simon300000** [comment]
不像是vtuber呀

**Comment by watatumi** [comment]
官宣加入VirtuaReal了，，大概，可能，应该算VUP了吧(ග⍛ග੭

**Comment by C-JIUJIE** [comment]
官宣加入VirtuaReal了，，大概，可能，应该算VUP了吧(ග⍛ග੭

**Comment by simon300000** [comment]
哇
那平时直播用皮吗？
在虚拟区直播吗？

**Comment by C-JIUJIE** [comment]
平时直播live3d，暂时还不在虚拟区但即将转入哦(๑•̀ㅂ•́)√

**Comment by simon300000** [comment]
啊哈，原来如此
